# Generated by Django 4.0.4 on 2022-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
